sonar.projectKey=tikto
sonar.organization=flavoriy
sonar.projectName=tikto

sonar.sources=src/app,src/components,src/lib,src/server,src/proxy.ts
sonar.tests=src/__tests__
sonar.test.inclusions=src/**/*.test.ts,src/**/*.spec.ts
sonar.exclusions=**/*.d.ts
sonar.coverage.inclusions=src/lib/**/*.ts,src/server/services/**/*.ts
sonar.coverage.exclusions=src/app/**/*,src/components/**/*,src/proxy.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
